### ISSUE TITLE
index.ts is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by sadaf2605** [godbasin/angular-select2#3]
```
ERROR in ./node_modules/angular-select2-component/index.ts
Module build failed: Error: /Users/sadafnoor/Projects/evaly/evaly-admin-ngapp/node_modules/angular-select2-component/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please openan issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/sadafnoor/Projects/evaly/evaly-admin-ngapp/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/Users/sadafnoor/Projects/evaly/evaly-admin-ngapp/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
 @ ./src/app/app.module.ts 16:34-70
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by godbasin** [comment]
Adding the include option at the end of tsconfig.json fixed the compile issue. 
Similar to #2
